---
header:
  version: 17
  includes:
    - kas/templates/bblayers.conf.yml
    - kas/templates/local-poky-v2.conf.yml

target: core_image_minimal

repos:
  bitbake:
    url: "https://git.openembedded.org/bitbake"
    branch: "2.8"
    path: "sources/bitbake"
    layers:
      .: disabled

  meta-yocto:
    url: "https://git.yoctoproject.org/meta-yocto"
    branch: "scarthgap"
    path: "sources/meta-yocto"
    layers:
      meta-poky:
      meta-yocto-bsp:

  meta-ti:
    url: "https://git.yoctoproject.org/meta-ti"
    branch: "scarthgap-wip"
    path: "sources/meta-ti"
    layers:
      meta-ti-extras:
      meta-ti-bsp:

  meta-arm:
    url: "https://git.yoctoproject.org/meta-arm"
    branch: "scarthgap"
    path: "sources/meta-arm"
    layers:
      meta-arm:
      meta-arm-toolchain:

  oe-core:
    url: "https://git.openembedded.org/openembedded-core"
    branch: "scarthgap"
    path: "sources/oe-core"
    layers:
      meta:
