BB_CONF_FRAGMENT_SUMMARY = "Config specific overrides for arago-master-next-config"
BB_CONF_FRAGMENT_DESCRIPTION = "Config specific overrides for arago-master-next-config"

OVERRIDES:append = ":recipe-${@os.path.basename(d.getVar('FILE'))}"
BRANCH:recipe-cadence-mhdp-fw_git.bb = "ti-linux-firmware-next"
BRANCH:recipe-cnm-wave-fw_git.bb = "ti-linux-firmware-next"
BRANCH:recipe-goodix-fw_git.bb = "ti-linux-firmware-next"
BRANCH:recipe-linux-ti-staging_6.18.bb = "ti-linux-6.18.y-cicd"
BRANCH:recipe-linux-ti-staging-rt_6.18.bb = "ti-linux-6.18.y-cicd"
BRANCH:recipe-prueth-fw_5.6.15.bb = "ti-linux-firmware-next"
BRANCH:recipe-pruhsr-fw_2.17.25.bb = "ti-linux-firmware-next"
BRANCH:recipe-pruprp-fw_2.17.25.bb = "ti-linux-firmware-next"
BRANCH:recipe-prusw-fw_3.2.9.bb = "ti-linux-firmware-next"
BRANCH:recipe-ti-dac-fw.bb = "ti-linux-firmware-next"
BRANCH:recipe-ti-dm-fw.bb = "ti-linux-firmware-next"
BRANCH:recipe-ti-eth-fw.bb = "ti-linux-firmware-next"
BRANCH:recipe-ti-hsm-demo-fw_git.bb = "ti-linux-firmware-next"
BRANCH:recipe-ti-pka-fw_git.bb = "ti-linux-firmware-next"
BRANCH:recipe-ti-rtos-echo-test-fw.bb = "ti-linux-firmware-next"
BRANCH:recipe-ti-rtos-messageq-test-fw_git.bb = "ti-linux-firmware-next"
BRANCH:recipe-ti-sci-fw_git.bb = "ti-linux-firmware-next"
BRANCH:recipe-u-boot-ti-staging_2026.01.bb = "ti-u-boot-2026.01-next"
BRANCH:recipe-vxd-dec-fw_git.bb = "ti-linux-firmware-next"
