BB_CONF_FRAGMENT_SUMMARY = "Config specific overrides for arago-master-luks-config"
BB_CONF_FRAGMENT_DESCRIPTION = "Config specific overrides for arago-master-luks-config"

DISTRO_FEATURES:append = " tpm luks"
