BB_CONF_FRAGMENT_SUMMARY = "Config specific overrides for processor-sdk/processor-sdk-master-selinux-12.00.00.07.04-config"
BB_CONF_FRAGMENT_DESCRIPTION = "Config specific overrides for processor-sdk/processor-sdk-master-selinux-12.00.00.07.04-config"

DISTRO_FEATURES:append = " acl xattr pam selinux"
